### ISSUE TITLE
Improve networking

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#11]

**Comment by EldianTitan** [comment]
I am writing this comment to get everyone up to speed on our video streaming situation.

We first considered using a simple custom backend. This was the solution that was used last year, and Kacper recommended that we go for something better this year. There are several video streaming codecs and the one we chose to got with is H.264. However, implementing H.264 in C++ or Python would be a pain, so instead we decided to use a tool called FFmpeg. This tool allows us to grab a video stream from the camera, encode it and transfer it over a network.

The driver available on the Rasberry PI that FFmpeg uses is called Video4Linux2 (V4L2 for short). By default this driver uses an older input format (YUYV 4:2:2) that only supports raw, uncompressed video with a max resolution of 800x600. This was a limitation because we might want to use a higher resolution than 800x600. Thankfully, the camera we have can also format its output as an MJPEG stream, which is compressed and supports up to 1920x1080.

The surface-side was significantly easier. I ended up using an OpenCV module for Python. OpenCV provides some classes for receiving and processing a video stream, so not much was up was required.

For anyone who is interested for more, I will push a more detailed guide later that explains everything I briefly talked about here
